//! `vk man`: the contracts this kernel speaks, read out of the schemas
//! themselves.
//!
//! A kernel whose syscalls are contracts owes its users a way to read them
//! without a checkout, so every schema is embedded in the binary. The table is
//! written by hand rather than generated by a build script: there is exactly
//! one list, it is visible in the source, and nothing in the build depends on
//! walking a directory at compile time. The cost is that a new schema could be
//! forgotten, which is what `every_schema_in_the_repository_is_in_the_table`
//! below exists to make impossible.
use anyhow::{anyhow, Result};
use serde_json::{Map, Value};

/// `(name, schema)` for every file under `contracts/schemas/`. The name is the
/// file name without `.schema.json`, which is what `vk man <name>` takes.
pub const SCHEMAS: &[(&str, &str)] = &[
    (
        "approval",
        include_str!("../../../contracts/schemas/approval.schema.json"),
    ),
    (
        "arch_manifest",
        include_str!("../../../contracts/schemas/arch_manifest.schema.json"),
    ),
    (
        "blob_envelope",
        include_str!("../../../contracts/schemas/blob_envelope.schema.json"),
    ),
    (
        "challenge",
        include_str!("../../../contracts/schemas/challenge.schema.json"),
    ),
    (
        "clearance",
        include_str!("../../../contracts/schemas/clearance.schema.json"),
    ),
    (
        "gate_verdict",
        include_str!("../../../contracts/schemas/gate_verdict.schema.json"),
    ),
    (
        "label",
        include_str!("../../../contracts/schemas/label.schema.json"),
    ),
    (
        "lease",
        include_str!("../../../contracts/schemas/lease.schema.json"),
    ),
    (
        "ledger_event",
        include_str!("../../../contracts/schemas/ledger_event.schema.json"),
    ),
    (
        "liveness_lease",
        include_str!("../../../contracts/schemas/liveness_lease.schema.json"),
    ),
    (
        "module_manifest",
        include_str!("../../../contracts/schemas/module_manifest.schema.json"),
    ),
    (
        "principal",
        include_str!("../../../contracts/schemas/principal.schema.json"),
    ),
    (
        "register",
        include_str!("../../../contracts/schemas/register.schema.json"),
    ),
    (
        "resume_event",
        include_str!("../../../contracts/schemas/resume_event.schema.json"),
    ),
    (
        "shred_event",
        include_str!("../../../contracts/schemas/shred_event.schema.json"),
    ),
    (
        "stop_event",
        include_str!("../../../contracts/schemas/stop_event.schema.json"),
    ),
    (
        "syscall_ctx",
        include_str!("../../../contracts/schemas/syscall_ctx.schema.json"),
    ),
    (
        "tuf_root",
        include_str!("../../../contracts/schemas/tuf_root.schema.json"),
    ),
    (
        "validator_manifest",
        include_str!("../../../contracts/schemas/validator_manifest.schema.json"),
    ),
];

/// The raw schema, exactly as `contracts/schemas/` has it.
pub fn schema(name: &str) -> Option<&'static str> {
    SCHEMAS.iter().find(|(n, _)| *n == name).map(|(_, s)| *s)
}

pub fn names() -> Vec<&'static str> {
    SCHEMAS.iter().map(|(n, _)| *n).collect()
}

/// What there is to read: the name to ask for, and the type it describes.
pub fn list() -> String {
    let w = names().iter().map(|n| n.len()).max().unwrap_or(0);
    SCHEMAS
        .iter()
        .map(|(name, raw)| {
            let title = serde_json::from_str::<Value>(raw)
                .ok()
                .and_then(|v| v["title"].as_str().map(str::to_owned))
                .unwrap_or_default();
            format!("{name:w$}  {title}").trim_end().to_string()
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// One contract as a synopsis: what it is, what it must carry, and what every
/// field means. Named types are resolved from the schema's own `$defs` one
/// level deep — deep enough to read an enum's values or an object's shape
/// without chasing a `$ref`, shallow enough that the page stays a page.
pub fn render(name: &str) -> Result<String> {
    let raw = schema(name).ok_or_else(|| unknown(name))?;
    let s: Value = serde_json::from_str(raw)?;
    let defs = s["$defs"].as_object().cloned().unwrap_or_default();
    let title = s["title"].as_str().unwrap_or(name);
    let mut out = vec![format!("{title}  —  contracts/schemas/{name}.schema.json")];
    if let Some(d) = s["description"].as_str() {
        out.push(d.to_string());
    }
    if let Some(variants) = s["oneOf"].as_array() {
        out.push("one of:".into());
        for v in variants {
            out.push(variant(v, &defs));
        }
        return Ok(out.join("\n\n"));
    }
    let required: Vec<&str> = s["required"]
        .as_array()
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    if !required.is_empty() {
        out.push(format!("required: {}", required.join(", ")));
    }
    match s["properties"].as_object() {
        Some(props) if !props.is_empty() => {
            out.push(format!(
                "properties:\n{}",
                properties(props, &required, &defs)
            ));
        }
        _ => out.push(format!("(no fields: {})", type_of(&s))),
    }
    Ok(out.join("\n\n"))
}

/// What `vk man <name>` says when there is no such name: the list, because the
/// name that was wanted is almost always in it under another spelling.
pub fn unknown(name: &str) -> anyhow::Error {
    anyhow!("no contract named {name}. There are these:\n\n{}", list())
}

/// One variant of a top-level `oneOf`, named by its discriminant where it has
/// one (`kind: "machine"`), which is how a reader tells them apart.
fn variant(v: &Value, defs: &Map<String, Value>) -> String {
    let props = v["properties"].as_object().cloned().unwrap_or_default();
    let name = props
        .iter()
        .find_map(|(k, p)| p["const"].as_str().map(|c| format!("{k} = \"{c}\"")))
        .unwrap_or_else(|| "variant".into());
    let required: Vec<&str> = v["required"]
        .as_array()
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    format!("  {name}\n{}", properties(&props, &required, defs))
}

/// The property block: one line per field, then its description, its values
/// and its shape indented under it.
fn properties(props: &Map<String, Value>, required: &[&str], defs: &Map<String, Value>) -> String {
    let w = props.keys().map(String::len).max().unwrap_or(0);
    let mut out = Vec::new();
    for (name, p) in props {
        let mark = if required.contains(&name.as_str()) {
            "  (required)"
        } else {
            ""
        };
        out.push(
            format!("    {name:w$}  {}{mark}", type_of(p))
                .trim_end()
                .to_string(),
        );
        let resolved = resolve(p, defs);
        for line in [p, &resolved]
            .iter()
            .filter_map(|v| v["description"].as_str())
        {
            out.push(format!("        {line}"));
        }
        if let Some(values) = resolved["enum"].as_array() {
            out.push(format!(
                "        values: {}",
                values.iter().map(compact).collect::<Vec<_>>().join(" | ")
            ));
        }
        // One level deep: a named object's own fields, but not their fields.
        if let Some(inner) = resolved["properties"].as_object() {
            let iw = inner.keys().map(String::len).max().unwrap_or(0);
            for (k, v) in inner {
                out.push(format!("        {k:iw$}  {}", type_of(v)));
            }
        }
    }
    out.join("\n")
}

/// A `$ref` into this schema's own `$defs`, followed once.
fn resolve(p: &Value, defs: &Map<String, Value>) -> Value {
    def_name(p)
        .and_then(|n| defs.get(&n).cloned())
        .unwrap_or(Value::Null)
}

fn def_name(p: &Value) -> Option<String> {
    p["$ref"]
        .as_str()?
        .strip_prefix("#/$defs/")
        .map(str::to_owned)
}

/// A field's type as a person would say it: the named type for a `$ref`, the
/// element type inside an array, `T or null` for an optional one. A `$ref` is
/// named, not followed, so this needs no `$defs`: following one is `resolve`'s
/// job, and only where a page has room for what it finds.
fn type_of(p: &Value) -> String {
    if let Some(n) = def_name(p) {
        return n;
    }
    if let Some(alts) = p["anyOf"].as_array().or_else(|| p["oneOf"].as_array()) {
        return alts.iter().map(type_of).collect::<Vec<_>>().join(" or ");
    }
    if let Some(c) = p["const"].as_str() {
        return format!("\"{c}\"");
    }
    match p["type"].as_str() {
        Some("array") => format!("array of {}", type_of(&p["items"])),
        Some("object") => match p["additionalProperties"].as_object() {
            Some(v) => format!("map of string to {}", type_of(&Value::Object(v.clone()))),
            None => "object".into(),
        },
        Some("integer") => match p["format"].as_str() {
            Some(f) => format!("integer ({f})"),
            None => "integer".into(),
        },
        Some(t) => t.into(),
        None => "any".into(),
    }
}

fn compact(v: &Value) -> String {
    v.as_str()
        .map(str::to_owned)
        .unwrap_or_else(|| v.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The one thing a hand-written table can get wrong. A schema added to
    /// `contracts/schemas/` and not to `SCHEMAS` would be a contract this
    /// kernel speaks and cannot show, so the directory is walked here and the
    /// two lists must agree exactly — in both directions, so a renamed file
    /// cannot leave a stale entry behind either.
    #[test]
    fn every_schema_in_the_repository_is_in_the_table() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../contracts/schemas");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .filter_map(|f| f.strip_suffix(".schema.json").map(str::to_owned))
            .collect();
        on_disk.sort();
        let mut embedded: Vec<String> = names().iter().map(|n| n.to_string()).collect();
        embedded.sort();
        assert_eq!(
            embedded, on_disk,
            "`vk man` and contracts/schemas/ disagree; add the missing entries to SCHEMAS"
        );
        assert!(
            !on_disk.is_empty(),
            "no schemas found under {}",
            dir.display()
        );
    }

    /// Every embedded schema parses and renders, so `vk man <anything in the
    /// list>` cannot be the call that discovers a malformed one.
    #[test]
    fn every_contract_renders() {
        for name in names() {
            let page = render(name).unwrap_or_else(|e| panic!("vk man {name}: {e}"));
            assert!(page.contains(name), "{name} page does not name its file");
            for line in page.lines() {
                assert_eq!(
                    line,
                    line.trim_end(),
                    "trailing whitespace in {name}: {line:?}"
                );
            }
        }
    }

    #[test]
    fn a_page_says_what_is_required_what_the_values_are_and_what_is_nested() {
        let page = render("label").unwrap();
        assert!(
            page.contains("required: scope, data_class, origins"),
            "{page}"
        );
        // A named enum resolved from $defs: its values, and its own docstring.
        assert!(page.contains("data_class  DataClass"), "{page}");
        assert!(
            page.contains("values: public | vertical | business | personal | holdout"),
            "{page}"
        );
        assert!(page.contains("array of Origin"), "{page}");

        // A named object one level deep: the fields of Hlc, under `hlc`.
        let page = render("ledger_event").unwrap();
        let field = |name: &str, ty: &str| {
            page.lines()
                .any(|l| l.trim().starts_with(&format!("{name} ")) && l.trim().ends_with(ty))
        };
        assert!(field("hlc", "Hlc  (required)"), "{page}");
        assert!(field("wall_ms", "integer (uint64)"), "{page}");
        assert!(field("counter", "integer (uint32)"), "nested Hlc: {page}");
        assert!(
            page.contains("Commits to ciphertext, never to plaintext"),
            "a field's own description belongs on the page: {page}"
        );

        // A contract that is a choice, not a record.
        let page = render("principal").unwrap();
        assert!(page.contains("one of:"), "{page}");
        assert!(page.contains("kind = \"machine\""), "{page}");
        assert!(page.contains("kind = \"human\""), "{page}");
    }

    #[test]
    fn an_unknown_name_is_told_what_there_is() {
        assert!(render("no-such-contract").is_err());
        let why = unknown("no-such-contract").to_string();
        assert!(why.contains("no-such-contract"), "{why}");
        assert!(
            why.contains("ledger_event"),
            "the list is in the error: {why}"
        );
    }
}
